### ISSUE TITLE
Create 5 resources

### ISSUE THREAD

**Issue by jk1510karti** [stelligent/stelligent_commons#2]
Hi,
I am trying to customize the template to create 5 resources (Number of Instances). But I have duplicated the existing blocks. but it when I provide numberof instance 5, it creates only 3.

Please let me know how to change the condition to create 5 instance.

**Comment by sclausson** [comment]
@jk1510karti please indicate to which cloudformation template you are refering.

**Comment by jk1510karti** [comment]
@sclausson the below one
https://github.com/stelligent/stelligent_commons/blob/master/cloudformation/codedeploy-ec2.json

**Comment by jk1510karti** [comment]
Any updated on this greatly appreciated.

**Comment by sclausson** [comment]
@jk1510karti the template is working as expected. It is only meant to deploy 1 to 3 instances. https://github.com/stelligent/stelligent_commons/blob/master/cloudformation/codedeploy-ec2.json#L37

**Comment by jk1510karti** [comment]
Yes, I would like to customize the template to create 5 resources. i.e. I will get number of instance from user, sometime user will create 3, sometime they will create 5. So how can I customize the template to create 5 EC2 resources.  I have made some modifications in the template. But I couldn't successful. Please review the below 

https://github.com/jk1510karti/jk/blob/master/codedeploy-ec2

**Comment by jk1510karti** [comment]
In the below template, If I mention "Number of Instance" as 4 means, it creates "LinuxEC2Instance4" & "LinuxEC2Instance" , If I mention 5 then it creates "LinuxEC2Instance5" & "LinuxEC2Instance". So I belive there is some mistake in the conditions part. Please assist to correct the same.

https://github.com/jk1510karti/jk/blob/master/codedeploy-ec2

**Comment by jk1510karti** [comment]
hi @sclausson any update on this?

**Comment by sclausson** [comment]
@jk1510karti if you are just wanting to deply 3 to 5 instances (instead of 1 to 3 instances, as the template is intended) then this should probably work for you (I don't have the time to deploy/test this for you)

https://gist.github.com/sclausson/f93beb521ba8675f69a452c8fe6e9c0d

**Comment by jk1510karti** [comment]
hi @sclausson no worries. I manged to add conditions, Now I can create number of instances based on the user inputs. Appreciate your time. :-)
